// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyykcpchxtbfnabuekcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5eWtjcGNoeHRiZm5hYnVla2N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0MDY2NzgsImV4cCI6MjA1Mjk4MjY3OH0.Oh_w773Jc51oyc05sfGKZlvhmTAz8W03USyVeuouQ10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);